language: python
python:
 - "3.6.2"

#dependacies and libraries to install
install: pip install -r requirements.txt

script:
  - nosetests --with-coverage

after_success:
  - coveralls
  - codeclimate-test-reporter


